In [6]:
import numpy as np
from criteria.multi_criteria import *

In [7]:
matrix = np.array([
    [459, 510, 6400,  16.2],
    [645, 570, 12800, 18.0],
    [639, 558, 51200, 20.1],
    [548, 492, 16000, 20.1],
    [677, 375, 25600, 20.3],
    [399, 247, 6400,  16.0]
])

alternatives = [
    "Nikon D5100", 
    "Canon EOS 700D", 
    "Pentax K-S1", 
    "Sony ALPHA SLT A58K", 
    "Samsung NX30", 
    "OLYMPUS TG-3"
]

maximization = [False, False, True, True]

In [8]:
print("--- 1. Metóda entropie ---")
vahy_entropia = metoda_entropie(matrix, info=True)
print(f"-> Výsledné váhy (Entropia): {np.round(vahy_entropia, 4)}\n")

print("--- 2. Metóda poradia ---")
vahy_poradia = metoda_poradia(ranks=[3, 4, 1, 2], info=True)
print(f"-> Výsledné váhy (Poradie): {np.round(vahy_poradia, 4)}\n")

print("--- 3. Fullerova metóda ---")
vahy_fuller = fullerova_metoda(frequencies=[3, 2, 1, 0], modified=True, info=True)
print(f"-> Výsledné váhy (Fuller - modifikovaná): {np.round(vahy_fuller, 4)}\n")

print("--- 4. Bodovacia metóda (pre váhy) ---")
vahy_bodovacia = bodovacia_metoda_vahy(body=[80, 50, 90, 60])
print(f"-> Výsledné váhy (Bodovacia): {np.round(vahy_bodovacia, 4)}\n")

print("--- 5. Saatyho metóda (pre váhy kritérií) ---")
S_matica = np.array([[1,   3,   1/3, 2],[1/3, 1,   1/5, 1/2],
    [3,   5,   1,   4],[1/2, 2,   1/4, 1]
])
vahy_saaty = saatyho_metoda_vahy(S_matica, info=True)
print(f"-> Výsledné váhy (Saaty): {np.round(vahy_saaty, 4)}\n")

print("--- 6. Postupný rozvrh váh ---")
vahy_postupne = postupny_rozvrh_vah(
    skupiny_vahy=[0.6, 0.4], 
    kriteria_v_skupinach_vahy=[[0.7, 0.3], [0.8, 0.2]],
    info=True
)
print(f"-> Výsledné váhy (Postupný rozvrh): {np.round(vahy_postupne, 4)}\n")

--- 1. Metóda entropie ---
Stĺpcové súčty: [3.367e+03 2.752e+03 1.184e+05 1.107e+02]
Entropia kritérií (E): [0.99030195 0.98104304 0.84835915 0.99721596]
-> Výsledné váhy (Entropia): [0.053  0.1035 0.8283 0.0152]

--- 2. Metóda poradia ---
Priradené váhy (v): [2 1 4 3]
-> Výsledné váhy (Poradie): [0.2 0.1 0.4 0.3]

--- 3. Fullerova metóda ---
Celkový počet porovnaní: 6.0
-> Výsledné váhy (Fuller - modifikovaná): [0.4 0.3 0.2 0.1]

--- 4. Bodovacia metóda (pre váhy) ---
-> Výsledné váhy (Bodovacia): [0.2857 0.1786 0.3214 0.2143]

--- 5. Saatyho metóda (pre váhy kritérií) ---
Geometrické priemery riadkov: [1.18920712 0.42728701 2.78315768 0.70710678]
-> Výsledné váhy (Saaty): [0.2329 0.0837 0.545  0.1385]

--- 6. Postupný rozvrh váh ---
Skupina 1: váha 0.6, váhy kritérií [0.7 0.3]
Skupina 2: váha 0.4, váhy kritérií [0.8 0.2]
-> Výsledné váhy (Postupný rozvrh): [0.42 0.18 0.32 0.08]



In [9]:
test_weights = vahy_postupne

aspiracne_urovne = [600, 500, 12000, 18.0]

print("--- 7. Konjunktívna metóda ---")
idx_konj = konjunktivna_metoda(matrix, aspiracne_urovne, maximalizacne=maximization)
print(f"-> Akceptované varianty (Konjunktívna): {[alternatives[i] for i in idx_konj]}\n")

print("--- 8. Disjunktívna metóda ---")
idx_disj = disjunktivna_metoda(matrix, aspiracne_urovne, maximalizacne=maximization)
print(f"-> Akceptované varianty (Disjunktívna): {[alternatives[i] for i in idx_disj]}\n")

print("--- 9. Metóda PRIAM ---")
idealny_bod =[399, 247, 51200, 20.3]
idx_priam, msg_priam, _ = metoda_priam_krok(
    matrix, 
    z_nove=aspiracne_urovne, 
    idealny_variant=idealny_bod, 
    maximization=maximization, 
    info=True
)
if isinstance(idx_priam, (list, np.ndarray)):
    print(f"-> Výsledok PRIAM: {[alternatives[i] for i in idx_priam]} ({msg_priam})\n")
else:
    print(f"-> Výsledok PRIAM: {alternatives[idx_priam]} ({msg_priam})\n")


--- 7. Konjunktívna metóda ---
-> Akceptované varianty (Konjunktívna): ['Canon EOS 700D', 'Pentax K-S1']

--- 8. Disjunktívna metóda ---
-> Akceptované varianty (Disjunktívna): ['Nikon D5100', 'Canon EOS 700D', 'Pentax K-S1', 'Sony ALPHA SLT A58K', 'Samsung NX30']

--- 9. Metóda PRIAM ---
Kontrola aspirácií [  600.   500. 12000.    18.]: splnené=[[ True False False False]
 [False False  True  True]
 [False False  True  True]
 [ True  True  True  True]
 [False  True  True  True]
 [ True  True False False]]
-> Výsledok PRIAM: Sony ALPHA SLT A58K (Najdeny jediny kompromisny variant)



In [10]:
print("--- 10. Metóda poradia variantov ---")
idx_poradia, P_mat, weighted_ranks = metoda_poradia_varianty(matrix, test_weights, maximization=maximization)
print(f"Matica poradí variantov:\n{P_mat}")
print(f"Vážené súčty poradí: {np.round(weighted_ranks, 4)}")
print(f"-> Najlepší variant: {alternatives[idx_poradia]}\n")

--- 10. Metóda poradia variantov ---
Matica poradí variantov:
[[2.  4.  5.5 5. ]
 [5.  6.  4.  4. ]
 [4.  5.  1.  2.5]
 [3.  3.  3.  2.5]
 [6.  2.  2.  1. ]
 [1.  1.  5.5 6. ]]
Vážené súčty poradí: [3.72 4.78 3.1  2.96 3.6  2.84]
-> Najlepší variant: OLYMPUS TG-3



In [11]:
print("--- 11. Lexikografická metóda ---")
# Poradie dôležitosti indexov: ISO(2) -> Cena(0) -> Rozlíšenie(3) -> Hmotnosť(1)
idx_lex = lexikograficka_metoda(matrix, poradie_kriterii=[2, 0, 3, 1], maximization=maximization)
print(f"Zostávajúce indexy po postupnom filtrovaní: {idx_lex}")
print(f"-> Najlepší variant(y): {[alternatives[i] for i in idx_lex]}\n")

--- 11. Lexikografická metóda ---
Zostávajúce indexy po postupnom filtrovaní: [2]
-> Najlepší variant(y): ['Pentax K-S1']



In [12]:
print("--- 12. Metóda váženého súčtu ---")
idx_wsa, U_mat, scores_wsa = metoda_vazeneho_suctu(matrix, test_weights, maximization=maximization)
print(f"Normalizovaná matica (U):\n{np.round(U_mat, 4)}")
print(f"Výsledné skóre variantov (G_i): {np.round(scores_wsa, 4)}")
print(f"-> Najlepší variant: {alternatives[idx_wsa]}\n")

--- 12. Metóda váženého súčtu ---
Normalizovaná matica (U):
[[ 0.7842  0.1858  0.      0.0465]
 [ 0.1151 -0.      0.1429  0.4651]
 [ 0.1367  0.0372  1.      0.9535]
 [ 0.464   0.2415  0.2143  0.9535]
 [-0.      0.6037  0.4286  1.    ]
 [ 1.      1.      0.      0.    ]]
Výsledné skóre variantov (G_i): [0.3665 0.1313 0.4604 0.3832 0.3258 0.6   ]
-> Najlepší variant: OLYMPUS TG-3



In [13]:
print("--- 13. Bodovacia metóda (pre varianty) ---")
scored_mock = np.random.randint(1, 11, size=matrix.shape)
print(f"Náhodne priradené body pre maticu:\n{scored_mock}")
idx_bod_var, G_i_bod = bodovacia_metoda_varianty(scored_mock, test_weights)
print(f"Vážené súčty bodov pre jednotlivé varianty: {np.round(G_i_bod, 4)}")
print(f"-> Najlepší variant: {alternatives[idx_bod_var]}\n")

--- 13. Bodovacia metóda (pre varianty) ---
Náhodne priradené body pre maticu:
[[ 2  4  9  7]
 [ 5  3  7  4]
 [ 4  8  1  9]
 [ 9  9  4  7]
 [ 3  4 10  6]
 [ 2  1  3  9]]
Vážené súčty bodov pre jednotlivé varianty: [5.   5.2  4.16 7.24 5.66 2.7 ]
-> Najlepší variant: Sony ALPHA SLT A58K



In [14]:
print("--- 14. Permutačná metóda ---")
best_perm, r_phi, C_mat = permutacna_metoda(matrix, test_weights, maximization=maximization)
print(f"Matica indexov súhlasu (C):\n{np.round(C_mat, 4)}")
print(f"Hodnota R_phi pre najlepšiu permutáciu: {r_phi}")
print(f"-> Najlepšie celkové poradie variantov: {[alternatives[i] for i in best_perm]}\n")

--- 14. Permutačná metóda ---
Matica indexov súhlasu (C):
[[0.   0.6  0.6  0.42 0.42 0.4 ]
 [0.4  0.   0.   0.   0.42 0.4 ]
 [0.4  1.   0.   0.4  0.74 0.4 ]
 [0.58 1.   0.68 0.   0.42 0.4 ]
 [0.58 0.58 0.26 0.58 0.   0.4 ]
 [0.92 0.6  0.6  0.6  0.6  0.  ]]
Hodnota R_phi pre najlepšiu permutáciu: 4.48
-> Najlepšie celkové poradie variantov: ['OLYMPUS TG-3', 'Sony ALPHA SLT A58K', 'Nikon D5100', 'Pentax K-S1', 'Samsung NX30', 'Canon EOS 700D']



In [15]:
print("--- 15. Metóda TOPSIS ---")
idx_topsis, c_i, d_plus, d_minus = metoda_topsis(matrix, test_weights, maximization=maximization)
print(f"Vzdialenosti od ideálneho variantu (d+): {np.round(d_plus, 4)}")
print(f"Vzdialenosti od bazálneho variantu (d-): {np.round(d_minus, 4)}")
print(f"-> Relatívne ukazovatele c_i: {np.round(c_i, 4)}")
print(f"-> Najlepší variant: {alternatives[idx_topsis]}\n")

--- 15. Metóda TOPSIS ---
Vzdialenosti od ideálneho variantu (d+): [0.2376 0.219  0.0868 0.1924 0.1585 0.2333]
Vzdialenosti od bazálneho variantu (d-): [0.0662 0.0349 0.2336 0.0648 0.1047 0.0975]
-> Relatívne ukazovatele c_i: [0.2179 0.1373 0.729  0.2519 0.3978 0.2947]
-> Najlepší variant: Pentax K-S1



In [16]:
print("--- 16. Metóda ORESTE ---")
# Ako vstupné poradia variantov pre ORESTE použijeme P_mat, ktorú sme získali z Metódy poradia
idx_oreste, r_sums, R_mat, D_mat = metoda_oreste_hodnotenie(q_ranks=[3, 4, 1, 2], P_matrix=P_mat, r=3)
print(f"Matica vzdialeností (D):\n{np.round(D_mat, 4)}")
print(f"Matica globálnych poradí (R):\n{R_mat}")
print(f"Súčty poradí pre varianty: {r_sums}")
print(f"-> Najlepší variant: {alternatives[idx_oreste]}\n")

--- 16. Metóda ORESTE ---
Matica vzdialeností (D):
[[2.5962 4.     4.3741 4.0514]
 [4.2358 5.1925 3.1913 3.3019]
 [3.57   4.5549 1.     2.2774]
 [3.     3.57   2.4101 2.2774]
 [4.9529 3.3019 1.651  1.651 ]
 [2.4101 3.1913 4.3741 4.8203]]
Matica globálnych poradí (R):
[[ 8.  16.  19.5 17. ]
 [18.  24.  10.5 12.5]
 [14.5 21.   1.   4.5]
 [ 9.  14.5  6.5  4.5]
 [23.  12.5  2.5  2.5]
 [ 6.5 10.5 19.5 22. ]]
Súčty poradí pre varianty: [60.5 65.  41.  34.5 40.5 58.5]
-> Najlepší variant: Sony ALPHA SLT A58K



In [17]:
print("--- 17. Metóda ELECTRE I ---")
eff_variants, P_matrix_electre, C_idx, D_idx = metoda_electre_I(matrix, test_weights, c_star=0.6, d_star=0.4, maximization=maximization)
print(f"Matica indexov zhody (C_ij):\n{np.round(C_idx, 4)}")
print(f"Matica indexov nezhody (D_ij):\n{np.round(D_idx, 4)}")
print(f"Výsledná matica preferencií P (0/1):\n{P_matrix_electre}")
if eff_variants:
    print(f"-> Efektívne (nedominované) varianty: {[alternatives[i] for i in eff_variants]}\n")
else:
    print("-> Nenašli sa jednoznačne efektívne varianty pre dané prahy c* a d*.\n")

--- 17. Metóda ELECTRE I ---
Matica indexov zhody (C_ij):
[[0.   0.6  0.6  0.42 0.42 0.4 ]
 [0.4  0.   0.   0.   0.42 0.4 ]
 [0.4  1.   0.   0.4  0.74 0.4 ]
 [0.58 1.   0.68 0.   0.42 0.4 ]
 [0.58 0.58 0.26 0.58 0.   0.4 ]
 [0.92 0.6  0.6  0.6  0.6  0.  ]]
Matica indexov nezhody (D_ij):
[[0.000e+00 1.429e-01 1.000e+00 2.143e-01 4.286e-01 5.900e-03]
 [4.200e-03 0.000e+00 8.571e-01 7.140e-02 2.857e-01 7.200e-03]
 [4.000e-03 0.000e+00 0.000e+00 2.000e-03 4.100e-03 6.900e-03]
 [2.000e-03 0.000e+00 7.857e-01 0.000e+00 2.143e-01 5.500e-03]
 [4.900e-03 7.000e-04 5.714e-01 2.900e-03 0.000e+00 6.200e-03]
 [0.000e+00 1.429e-01 1.000e+00 2.143e-01 4.286e-01 0.000e+00]]
Výsledná matica preferencií P (0/1):
[[0 1 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 0 1 0 0]]
-> Efektívne (nedominované) varianty: ['Pentax K-S1', 'OLYMPUS TG-3']



In [18]:
print("--- 18. Metóda AGREPREF ---")
agrepref_relations = metoda_agrepref(matrix, test_weights, alpha=0.5, beta=0.1, maximization=maximization)
print(f"Výsledná matica relácií AGREPREF (1=P, 2=I, 3=N):\n{agrepref_relations}")

--- 18. Metóda AGREPREF ---
Výsledná matica relácií AGREPREF (1=P, 2=I, 3=N):
[[0 1 1 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 1 0]
 [1 1 1 0 0 0]
 [1 1 0 1 0 0]
 [1 1 1 1 1 0]]


In [19]:
print("--- 19. Metóda AHP (pre varianty) ---")
saaty_krit_mock = np.ones((4, 4)) 
zoznam_saaty_var_mock =[np.ones((6, 6)) for _ in range(4)]
idx_ahp_var, ahp_scores, var_weights_mat = metoda_ahp_varianty(saaty_krit_mock, zoznam_saaty_var_mock)
print(f"Lokálne váhy variantov pre každé kritérium:\n{np.round(var_weights_mat, 4)}")
print(f"Celkové skóre variantov:\n{np.round(ahp_scores, 4)}")
print(f"-> Najlepší variant: {alternatives[idx_ahp_var]}\n")

--- 19. Metóda AHP (pre varianty) ---
Lokálne váhy variantov pre každé kritérium:
[[0.1667 0.1667 0.1667 0.1667]
 [0.1667 0.1667 0.1667 0.1667]
 [0.1667 0.1667 0.1667 0.1667]
 [0.1667 0.1667 0.1667 0.1667]
 [0.1667 0.1667 0.1667 0.1667]
 [0.1667 0.1667 0.1667 0.1667]]
Celkové skóre variantov:
[0.1667 0.1667 0.1667 0.1667 0.1667 0.1667]
-> Najlepší variant: Nikon D5100

