In [1]:
from criteria import criteria
import numpy as np

In [2]:
payoff_matrix = np.array(
    [ 
        [100,70,-20],
        [160,60,-10],
        [130,65,5],
        [200,80,-40]
    ]
)

desicion_name = ['Wheat\t\t\t  ','Corn\t\t\t  ', 'Soybeans\t\t  ','Organic Vegetables']

for i in range(len(desicion_name)):
    print(f'{desicion_name[i]} | {payoff_matrix[i]}')

Wheat			   | [100  70 -20]
Corn			   | [160  60 -10]
Soybeans		   | [130  65   5]
Organic Vegetables | [200  80 -40]


In [3]:
alpha = 0.3
probabilities = [0.1, 0.3, 0.6]

In [4]:
pes_index = criteria.pesimisticke(payoff_matrix,info=True)
print(f'{desicion_name[pes_index]}')

--- Pesimistické (Waldovo) kritérium ---
Minimá po riadkoch (G_i): [-20 -10   5 -40]
Soybeans		  


In [5]:
opt_index = criteria.optimicke(payoff_matrix,info=True)
print(f'{desicion_name[opt_index]}')

--- Optimistické kritérium ---
Maximá po riadkoch (G_i): [100 160 130 200]
Organic Vegetables


In [6]:
hurwiczovo_index = criteria.hurwiczovo(payoff_matrix, alpha,info=True)
print(f'{desicion_name[hurwiczovo_index]} ')

--- Hurwiczovo kritérium (alpha=0.3) ---
Hodnoty G_i pre každý riadok: [16.  41.  42.5 32. ]
Soybeans		   


In [7]:
savageovo_index = criteria.savageovo(payoff_matrix,info=True)
print(f'{desicion_name[savageovo_index]} ')

--- Savageovo (minimax regret) kritérium ---
Maximá v stĺpcoch: [200  80   5]
Matica ľútosti (Regret matrix):
[[100  10  25]
 [ 40  20  15]
 [ 70  15   0]
 [  0   0  45]]
Maximálne straty po riadkoch (G_i): [100  40  70  45]
Corn			   


In [8]:
print(f'Pravdepodobnosti: {probabilities}')

bayes_index = criteria.bayesovo(payoff_matrix,probabilities,info=True)
print(f'{desicion_name[bayes_index]}')

Pravdepodobnosti: [0.1, 0.3, 0.6]
--- Bayesovo kritérium ---
Očakávané zisky po riadkoch (G_i): [19.  28.  35.5 20. ]
Soybeans		  


In [9]:
laplac_index = criteria.laplaceovo(payoff_matrix,info=True)
print(f'{desicion_name[laplac_index]}')

--- Bayesovo kritérium ---
Očakávané zisky po riadkoch (G_i): [50.         70.         66.66666667 80.        ]
Organic Vegetables


In [10]:
hayashiho_index = criteria.hayashiho(payoff_matrix,info=True)
print(f'{desicion_name[hayashiho_index]}')

--- Hayashiho kritérium ---
Minimá v stĺpcoch: [100  60 -40]
Upravená matica g_ij:
[[  0  10  20]
 [ 60   0  30]
 [ 30   5  45]
 [100  20   0]]
Minimá po riadkoch (G_i): [0 0 5 0]
Soybeans		  


In [11]:
print(f'Pravdepodobnosti: {probabilities}')

osp_index = criteria.ocakavanej_strarty_prilezitosti(payoff_matrix,probabilities,info=True)
print(f'{desicion_name[osp_index]}')

Pravdepodobnosti: [0.1, 0.3, 0.6]
--- Kritérium očakávanej straty príležitosti ---
Matica ľútosti (Regret matrix):
[[100  10  25]
 [ 40  20  15]
 [ 70  15   0]
 [  0   0  45]]
Očakávané straty po riadkoch (G_i): [28.  19.  11.5 27. ]
Soybeans		  


In [12]:
print(f'Pravdepodobnosti: {probabilities} | α parametr = {alpha}')

hodges_lehmannovo_index = criteria.hodges_lehmannovo(payoff_matrix,alpha, probabilities,info=True)
print(f'{desicion_name[hodges_lehmannovo_index]}')

Pravdepodobnosti: [0.1, 0.3, 0.6] | α parametr = 0.3
--- Hodges-Lehmannovo kritérium (alpha=0.3) ---
Hodnoty G_i pre každý riadok: [ 7.3  16.6  26.35  2.  ]
Soybeans		  


In [13]:
hurwics_savageovo_index = criteria.hurwics_savageovo(payoff_matrix,alpha,info=True)
print(f'{desicion_name[hurwics_savageovo_index]}')

--- Hurwicz-Savageovo kritérium (alpha=0.3) ---
Matica ľútosti:
[[100  10  25]
 [ 40  20  15]
 [ 70  15   0]
 [  0   0  45]]
Hodnoty G_i po riadkoch: [64.  25.  50.5 19.5]
Organic Vegetables


In [14]:
print(f'Pravdepodobnosti: {probabilities}')

hermeyerovo_index = criteria.hermeyerovo(payoff_matrix,probabilities,info=True)
print(f'{desicion_name[hermeyerovo_index]}')

Pravdepodobnosti: [0.1, 0.3, 0.6]
--- Hermeyerovo kritérium ---
Matica prenásobená pravdepodobnosťami:
[[ 10.   21.  -12. ]
 [ 16.   18.   -6. ]
 [ 13.   19.5   3. ]
 [ 20.   24.  -24. ]]
Minimá po riadkoch (G_i): [-12.  -6.   3. -24.]
Soybeans		  


In [15]:
print(f'Pravdepodobnosti: {probabilities}')

najpravdepodobnejsi_stav_index = criteria.najpravdepodobnejsi_stav(payoff_matrix,probabilities,info=True)
print(f'{desicion_name[najpravdepodobnejsi_stav_index]}')

Pravdepodobnosti: [0.1, 0.3, 0.6]
--- Kritérium najpravdepodobnejšieho stavu ---
Najpravdepodobnejší stav (index stĺpca k): 2 (Pravdepodobnosť: 0.6)
Hodnoty v tomto stĺpci: [-20 -10   5 -40]
Maximálna hodnota (g_r): 5
Soybeans		  


In [17]:
starr_index = criteria.starrovo_domenove(payoff_matrix,info=True)
print(f'{desicion_name[starr_index]}')

--- Starrovo doménové kritérium (vzoriek: 100000) ---
Počet 'víťazstiev' pre jednotlivé riadky: [    0  1851 28225 69924]
Plošný obsah domén (podiel): [0.      0.01851 0.28225 0.69924]
Organic Vegetables


In [18]:
sucinove_index = criteria.sucinove(payoff_matrix,info=True)
print(f'{desicion_name[sucinove_index]}')

--- Súčinové kritérium ---
Matica obsahovala nekladné prvky. Upravená matica (+41):
[[141 111  21]
 [201 101  31]
 [171 106  46]
 [241 121   1]]
Súčiny po riadkoch (G_i): [328671 629331 833796  29161]
Soybeans		  


In [19]:
apo_index = criteria.apo(payoff_matrix, alpha,info=True)
print(f'{desicion_name[apo_index]}')

--- Modifikované Hurwiczovo (APO) kritérium (alpha=0.3) ---
Konštanta C: 1
Zotriedená matica (klesajúco):
[[100  70 -20]
 [160  60 -10]
 [130  65   5]
 [200  80 -40]]
A_max (priemer 1 najväčších): [100. 160. 130. 200.]
A_min (priemer 1 najmenších): [-20. -10.   5. -40.]
Výsledné hodnoty H_i: [16.  41.  42.5 32. ]
Soybeans		  


In [20]:
cumulative_max_index = criteria.cumulative_max_gaspars_wieloch(payoff_matrix,info=True)
print(f'{desicion_name[cumulative_max_index]}')

--- Kumulatívne maximinové kritérium radosti ---
Súčty v stĺpcoch: [590 275 -65]
Nová matica T^C (kumulatívnych ziskov):
[[-190    5  -15]
 [  50  -35   25]
 [ -70  -15   85]
 [ 210   45  -95]]
Minimá po riadkoch (G^C_i): [-190  -35  -70  -95]
Corn			  


In [21]:
dominant_radosti_index = criteria.dominant_radosti(payoff_matrix,info=True)
print(f'{desicion_name[dominant_radosti_index]}')

--- Dominančné kritérium radosti ---
Matica indexov p^j(g_ij) [P]:
[[4 2 3]
 [2 4 2]
 [3 3 1]
 [1 1 4]]
Matica T^D (m - P):
[[0 2 1]
 [2 0 2]
 [1 1 3]
 [3 3 0]]
Súčty po riadkoch (G^D_i): [3 4 5 6]
Organic Vegetables
